### ISSUE TITLE
How do you convert a Go time.Time to year float64?

### ISSUE THREAD

**Issue by carlmjohnson** [soniakeys/meeus#5]
Many functions take a float64 year, which makes sense since that was what the book you were working with had in it, but in Go, the normal way to use time is with the builtin time.Time. For example, to find out what day it is, you use `time.Now()`. But how do you convert that to a float64 year? I couldn't find a conversion function in your examples, and it feels non-trivial to work out: e.g. in a leap year, you have to divide by 365, time zones, etc.

**Comment by carlmjohnson** [comment]
I found `julian.TimeToJD`. Is that what I should use?

**Comment by ChristopherRabotin** [comment]
There are many ways to represent time in a float 64. If you're looking for
the Julian date time, then yes, use TimeToJD.

**Comment by soniakeys** [comment]
You could ask about specific functions, but for example the functions in the moonphase package aren't relying on the input year value being precise.  Internally, if you look at the code, there's a math.Floor in the snap() function that quantizes the float year into an integer representing a lunar cycle.  It might seem sloppy but base.JDEToJulianYear(julian.TimeToJD(t)) should work.
