### ISSUE TITLE
bug in coord.go

### ISSUE THREAD

**Issue by folgorante** [soniakeys/meeus#6]
Hi,
Thanks for the beautiful library!
I think I have found a bug in coord.go
Regards.
Marco

This is my diff:
```
diff coord.go.orig coord.go
230c230
< 	sδ, cδ := ψ.Sincos()
---
> 	sδ, cδ := δ.Sincos()
```

**Comment by soniakeys** [comment]
Hello Marco,
Thanks so much for the bug report.  This should be fixed and I added test coverage for it.
